name: Publish to NPM 📦

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to publish'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Tests:checkout"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}
      
      - name: "Tests:run"
        run: docker compose run tests yarn test
  
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: "Publish:checkout"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '23.x'
          registry-url: 'https://registry.npmjs.org'
      - name: "Enable corepack"
        run: corepack enable
        
      - name: "Publish:install"
        run: yarn
      
      - name: "Publish:build"
        run: yarn build

      - name: "Publish:publish package on NPM 📦"
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


    
