name: Publish to GitHub Packages 📦

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git reference to publish (tag, branch, or commit SHA)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Publish:checkout"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '23.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@janzal'
      
      - name: "Enable corepack"
        run: corepack enable
        
      - name: "Publish:install"
        run: yarn
      
      - name: "Publish:build"
        run: yarn build

      - name: "Configure package for GitHub Packages"
        run: |
          node -e "const fs = require('fs'); const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8')); pkg.name = '@janzal/nodemailer-mjml'; pkg.publishConfig = { '@janzal/registry': 'https://npm.pkg.github.com' }; fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));"

      - name: "Publish:publish package on GitHub Packages 📦"
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
